"""First-launch setup wizard — prompts for API keys and creates .env."""
from __future__ import annotations

from pathlib import Path

from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt, Confirm

console = Console()

ENV_PATH = Path(__file__).parent.parent.parent.parent / ".env"


def needs_setup() -> bool:
    """Check if first-launch setup is needed. Only triggers if .env doesn't exist at all."""
    return not ENV_PATH.exists()


def run_setup() -> None:
    """Interactive first-launch setup wizard."""
    console.print(
        Panel(
            "[bold cyan]🕸  spider.Web — First Launch Setup[/bold cyan]\n\n"
            "[dim]spider.Web uses Opus (Claude) as the central brain to route tasks.\n"
            "Local models handle research, chat, and automation.\n"
            "Cloud APIs (optional) enable the Opus orchestrator and Code Team.[/dim]",
            border_style="cyan",
        )
    )

    console.print()
    console.print("[bold]API Keys[/bold] [dim](press Enter to skip — local-only mode)[/dim]")
    console.print()

    anthropic_key = Prompt.ask(
        "[cyan]Anthropic API Key[/cyan] [dim](for Opus orchestrator)[/dim]",
        default="",
        show_default=False,
    )

    openai_key = Prompt.ask(
        "[cyan]OpenAI API Key[/cyan] [dim](for Codex code collaboration)[/dim]",
        default="",
        show_default=False,
    )

    # Write .env
    env_content = f"""# spider.Web Configuration
# Generated by first-launch setup

# Cloud API Keys
ANTHROPIC_API_KEY={anthropic_key}
OPENAI_API_KEY={openai_key}

# Ollama
OLLAMA_BASE_URL=http://localhost:11434

# Database
DATABASE_URL=postgresql+asyncpg://hub:hub_local_dev@localhost:5434/agentic_hub

# Redis
REDIS_URL=redis://localhost:6380/0

# Server
HUB_HOST=0.0.0.0
HUB_PORT=8420
"""
    ENV_PATH.write_text(env_content)
    console.print(f"\n[green]✓ Saved to {ENV_PATH}[/green]")

    # Summary
    has_anthropic = bool(anthropic_key)
    has_openai = bool(openai_key)

    console.print()
    if has_anthropic and has_openai:
        console.print(
            Panel(
                "[bold green]Full mode activated[/bold green]\n"
                "• Opus orchestrator: [green]ON[/green]\n"
                "• Code Team (Opus ↔ Codex): [green]ON[/green]\n"
                "• Local agents: [green]ON[/green]",
                border_style="green",
            )
        )
    elif has_anthropic:
        console.print(
            Panel(
                "[bold yellow]Partial mode[/bold yellow]\n"
                "• Opus orchestrator: [green]ON[/green]\n"
                "• Code Team: [red]OFF[/red] (needs OpenAI key)\n"
                "• Local agents: [green]ON[/green]",
                border_style="yellow",
            )
        )
    elif has_openai:
        console.print(
            Panel(
                "[bold yellow]Partial mode[/bold yellow]\n"
                "• Opus orchestrator: [red]OFF[/red] (needs Anthropic key)\n"
                "• Code Team: [red]OFF[/red] (needs both keys)\n"
                "• Local agents: [green]ON[/green]\n"
                "• Routing: keyword-based fallback",
                border_style="yellow",
            )
        )
    else:
        console.print(
            Panel(
                "[bold cyan]Local-only mode[/bold cyan]\n"
                "• Opus orchestrator: [red]OFF[/red]\n"
                "• Code Team: [red]OFF[/red]\n"
                "• Local agents: [green]ON[/green]\n"
                "• Routing: keyword-based fallback\n\n"
                "[dim]Add API keys later by editing .env[/dim]",
                border_style="cyan",
            )
        )

    console.print("\n[dim]Start the server with:[/dim] [bold]hub serve[/bold]")
    console.print("[dim]Then chat with:[/dim] [bold]hub chat[/bold]\n")
